[package]
name = "ag_file_system_scanner"
version = "0.1.0"
edition = "2021"
license = "MIT"
license-file = "LICENSE"
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.23"
